
export const auth = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGIN_PENDING: 'AUTH_LOGIN_PENDING',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_AUTHORIZE_SUCCESS: 'AUTH_AUTHORIZE_SUCCESS',
  AUTH_AUTHORIZE_ERROR: 'AUTH_AUTHORIZE_ERROR',
  AUTH_AUTHORIZE_PENDING: 'AUTH_AUTHORIZE_PENDING',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  AUTH_REGISTER_PENDING: 'AUTH_REGISTER_PENDING',
}

export const cart = {
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  GET_CART_ERROR: 'GET_CART_ERROR',
  GET_CART_PENDING: 'GET_CART_PENDING',
}

export const removeFromCart = {
  REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_ERROR: 'REMOVE_FROM_CART_ERROR',
  REMOVE_FROM_CART_PENDING: 'REMOVE_FROM_CART_PENDING',
}

export const addToCart = {
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_ERROR: 'ADD_TO_CART_ERROR',
  ADD_TO_CART_PENDING: 'ADD_TO_CART_PENDING',
}

export const order = {
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_ERROR: 'GET_ORDER_ERROR',
  GET_ORDER_PENDING: 'GET_ORDER_PENDING',
}
